import { ItemsList } from "@/components/BubbleCloud";

const MyTechStackArray: ItemsList[] = [
  {
    id: 1,
    proficiency: 100,
    color: "bg-[#61dafb]",
    text: "React",
    category: "frontend",
    textColor: "text-black",
  },
  { id: 2, proficiency: 80, color: "bg-[#1C1E26]", text: "Next.js", category: "frontend" },
  {
    id: 3,
    proficiency: 80,
    color: "bg-[#F7E025]",
    text: "JavaScript",
    category: "frontend",
    textColor: "text-black",
  },
  { id: 4, proficiency: 70, color: "bg-[#0077b6]", text: "TypeScript", category: "frontend" },
  { id: 5, proficiency: 30, color: "bg-[#74B152]", text: "Node.js", category: "backend" },
  {
    id: 6,
    proficiency: 50,
    color: "bg-[#5585A3]",
    text: "Java",
    category: "backend",
  },
  {
    id: 7,
    proficiency: 60,
    color: "bg-[#77BC1F]",
    text: "Spring Boot",
    category: "backend",
    textColor: "text-black",
  },
  { id: 8, proficiency: 60, color: "bg-[#37614d]", text: "MySQL", category: "database" },
  { id: 9, proficiency: 60, color: "bg-[#3e9cda]", text: "PostgreSQL", category: "database" },
  { id: 10, proficiency: 60, color: "bg-[#67b7d1]", text: "MongoDB", category: "database" },
  { id: 11, proficiency: 70, color: "bg-[#563d7c]", text: "Bootstrap", category: "frontend" },
  { id: 12, proficiency: 100, color: "bg-[#e44d26]", text: "HTML", category: "frontend" },
  { id: 13, proficiency: 90, color: "bg-[#264de4]", text: "CSS", category: "frontend" },
  {
    id: 14,
    proficiency: 50,
    color: "bg-[#58C4DC]",
    text: "React Native",
    category: "others",
    textColor: "text-black",
  },
  { id: 15, proficiency: 30, color: "bg-[#1A1A1A]", text: "Expo", category: "others" },
  {
    id: 16,
    proficiency: 50,
    color: "bg-[#9FEAF9]",
    text: "Electron",
    category: "others",
    textColor: "text-black",
  },
  { id: 17, proficiency: 40, color: "bg-[#28A8F6]", text: "Photoshop", category: "others" },
  { id: 18, proficiency: 85, color: "bg-[#15C213]", text: "Jest", category: "frontend" },
  { id: 19, proficiency: 85, color: "bg-[#93BD1D]", text: "Vitest", category: "frontend" },
  { id: 20, proficiency: 95, color: "bg-[#38bdf8]", text: "Tailwind CSS", category: "frontend" },
  { id: 21, proficiency: 40, color: "bg-[#232f3e]", text: "AWS", category: "others" },
  { id: 22, proficiency: 50, color: "bg-[#f1502f]", text: "Git", category: "others" },
  { id: 23, proficiency: 50, color: "bg-[#764abc]", text: "Redux", category: "frontend" },
  { id: 24, proficiency: 50, color: "bg-[#5d5f60]", text: "Zustand", category: "frontend" },
  { id: 26, proficiency: 80, color: "bg-[#ff4154]", text: "React Query", category: "frontend" },
  { id: 27, proficiency: 80, color: "bg-[#ff4785]", text: "Storybook", category: "frontend" },
  { id: 28, proficiency: 60, color: "bg-[#1c1e26]", text: "Express.js", category: "backend" },
  {
    id: 29,
    proficiency: 60,
    color: "bg-[#E52655]",
    text: "NestJS",
    category: "backend",
  },
  { id: 30, proficiency: 50, color: "bg-[#DD0031]", text: "Angular", category: "frontend" },
  { id: 31, proficiency: 70, color: "bg-[#FC6D26]", text: "GitLab", category: "others" },
  {
    id: 32,
    proficiency: 50,
    color: "bg-[#FFFFFF]",
    text: "GitHub",
    category: "others",
    textColor: "text-black",
  },
];

export default MyTechStackArray;
